### ISSUE TITLE
`prefers-color-scheme` doens't work when using Firefox

### ISSUE THREAD

**Issue by thetaPC** [stackblitz/core#2636]
### **Description of Bug**

`prefers-color-scheme` is not being respected when viewing the project on Firefox. 

While, Safari and Chrome respects `prefers-color-scheme` without any issues. I also experience no issue when using `prefers-color-scheme` + Firefox + Codepen.

### **Steps to Reproduce**

1. Go to https://stackblitz.com/edit/web-platform-98r8wn?file=styles.css
2. Open your OS's system settings
3. Toggle between dark and light
4. Notice that the styling stays the same regardless of theme

### **Expected Behavior**

I expect `prefers-color-scheme` to be respected regardless of browser.

### **Screenshots/Screencast**

From left to right: Chrome, Safari, Firefox.

https://github.com/stackblitz/core/assets/13530427/e6e98529-660d-4daf-9ecb-9b7b1eab57ad

**Additional Context/Questions**

In case the link doesn't work in the future:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Home</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width" />
    <!--
      Need a visual blank slate?
      Remove all code in `styles.css`!
    -->
    <link rel="stylesheet" href="styles.css" />
    <script type="module" src="script.js"></script>
  </head>
  <body>
    <main>
      <h1 class="theme-a">Home page</h1>
    </main>
  </body>
</html>
```

```css
.theme-a {
  background: #dca;
  color: #731;
}
@media (prefers-color-scheme: dark) {
  .theme-a {
    background: #753;
    color: #dcb;
    outline: 5px dashed #000;
  }
}
```
