### ISSUE TITLE
Import projects from GitLab & BitBucket

### ISSUE THREAD

**Issue by fmsouza** [stackblitz/core#75]
It would be great if I could import my projects from Gitlab too.

**Comment by DenisVuyka** [comment]
Are there any technical difficulties, or we just need to give you guys some time to go the integration? Thanks in advance.

**Comment by heavybeard** [comment]
News about this?

**Comment by SeriousM** [comment]
Any updates on this? I would love to see the integration happen!

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)

**Comment by bschelling** [comment]
Am I too impatient? Is it next month already?

**Comment by snpranav** [comment]
This issue hasn't been solved on the hosted version of StackBlitz on [stackblitz.com](https://stackblitz.com). Any updates on the GitLab integration @purplem1lk?

Please reopen this issue, so the integrations can be implemented.

**Comment by k33g** [comment]
@snpranav at the end I gave it a try to [GitPod](https://www.gitpod.io/), since then, it's my day to day IDE with a perfect GitLab integration

**Comment by snpranav** [comment]
@k33g Same here, I just moved to [GitPod](https://gitpod.io/) recently, and I'm loving the prebuilds, and the ability to run multiple workspaces without seeing my computer struggle for resources to run dev servers/programs simultaneously :sweat_smile:

**Comment by janstadt** [comment]
Any update on this? Would really love to be able to keep track of modifications directly in our own self hosted instance of bitbucket datacenter.

**Comment by mpcref** [comment]
Just in case anyone wants to bring their interest for this issue to GitLab's attention:
https://gitlab.com/gitlab-org/gitlab/-/issues/22414#note_818442359
https://gitlab.com/gitlab-org/gitlab/-/issues/197206#note_818438893

**Comment by mpcref** [comment]
@purplem1lk please reopen this issue. We're all eagerly awaiting GitLab support.

**Comment by rayfoss** [comment]
I heard 11 days ago @HeyGarrison will reopen this, and unleash a PR to end Github as we know it.

**Comment by HeyGarrison** [comment]
Back by popular demand, I present this issue. ❤️❤️❤️

For clarity, this isn't currently on the roadmap. I did see an amazing demo around git today, but it'll launch with GitHub support initially.

However, since I have this opportunity... Does everyone here use both gitlab/bitbucket and GitHub? What are you using for what (I.e. is one for work and one for open source)?

**Comment by rayfoss** [comment]
After trying to live with the isomorphic-git workaround, I encountered a show stopping push issue with web containers. I tried to debug it by importing the isomorphic-git repo to the Stackblitz IDE, but it's 1000+ commits seem to bog down the IDE to the point that it's unusable. The only way to debug it seems to modify node_modules directly.

Here's my new workaround, use GH as a proxy for Gitlab, powered by a GH action. MY_GH_KEY is just an SSH private key I've loaded into Gitlab as a repository Deploy Key with write access.

```
name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      # Runs a set of commands using the runners shell
      - name: Push to Gitlab
        env:
          MY_GH_KEY: ${{ secrets.MY_GH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$MY_GH_KEY" > ~/.ssh/id_ed25519
          ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/known_hosts
          git push git@gitlab.com:steam/deck-os.git
```
